### ISSUE TITLE
Reading wrong rotation

### ISSUE THREAD

**Issue by stefan-ax** [salykovaa/instant-DexNerf#1]
Hi and Thanks for your work!

I am trying to get the repo running with my own data. However, the extrinsics get messed up when loaded (they should point inward, not outward the circle):

![image](https://user-images.githubusercontent.com/51788429/186196632-37fea082-d0b4-4509-b87a-459be36db7ee.png)

I want to mention that the poses were generated with COLMAP in a `transforms.json` file. They are displayed correctly by `instant-ngp` and produce good results. 

Also, I am getting this error when I try to start the training, which is probably because of it not being able to build the rays from the positions.
```bash
WARNING  Nerf training generated 0 samples. Aborting training.
```

**Comment by salykova** [comment]
Hi Stefan!

It is because I cleaned original NGP code and removed all camera transformations from NeRF convention to NGP convention. Compare these functions with original NGP implementation: 

[nerf_direction_to_ngp](https://github.com/salykovaa/instant-DexNerf/blob/main/include/neural-graphics-primitives/nerf_loader.h#L97) vs. [original nerf_direction_to_ngp](https://github.com/NVlabs/instant-ngp/blob/master/include/neural-graphics-primitives/nerf_loader.h#L103)
[nerf_matrix_to_ngp](https://github.com/salykovaa/instant-DexNerf/blob/main/include/neural-graphics-primitives/nerf_loader.h#L102) vs. [original nerf_matrix_to_ngp](https://github.com/NVlabs/instant-ngp/blob/master/include/neural-graphics-primitives/nerf_loader.h#L113)
[ngp_matrix_to_nerf](https://github.com/salykovaa/instant-DexNerf/blob/main/include/neural-graphics-primitives/nerf_loader.h#L108) vs. [original ngp_matrix_to_nerf](https://github.com/NVlabs/instant-ngp/blob/master/include/neural-graphics-primitives/nerf_loader.h#L133)
[nerf_ray_to_ngp](https://github.com/salykovaa/instant-DexNerf/blob/main/include/neural-graphics-primitives/nerf_loader.h#L114) vs. [original nerf_ray_to_ngp](https://github.com/NVlabs/instant-ngp/blob/master/include/neural-graphics-primitives/nerf_loader.h#L151)

So, extrinsics are expected to be in the opencv format. You can either use original functions and recompile the project, or transform your extrinsics before load to json file. For more information see this [discussion](https://github.com/NVlabs/instant-ngp/discussions/153).
I hope this solves the problem. If not, please reopen the issue.
